version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped 